name: easy_wrf
channels:
  - conda-forge
dependencies:
  - clang_osx-64
  - clangxx_osx-64
  - gfortran_osx-64
  - boost-cpp
  - mpich
  - netcdf-cxx4
  - netcdf-fortran
  - netcdf4
  - jasper
  - libpng
  - zlib
  - hdf5
  - ncl
  - libssh
  - netcdf4
  - libnetcdf
  - netcdf-fortran
  - netcdf-cxx4
  - jinja2