package:
  name: easy_wrf
  version: 0.0.1

source:
  url: https://github.com/acs14007/easy_wrf/archive/refs/tags/v0.0.1.tar.gz
  sha256: a6ca18c5d6752eb2f6cd6a0c17228204ccc37f4a634957b4711fe9c3afbbd905

requirements:
  run:
    - python>=3.9
    - gfortran
    - gcc
    - cxx-compiler
    - boost-cpp
    - mpich
    - netcdf-cxx4
    - netcdf-fortran
    - netcdf4
    - jasper
    - libpng
    - zlib
    - hdf5
    - ncl
    - libssh
    - netcdf4
    - libnetcdf
    - netcdf-fortran
    - netcdf-cxx4
    - jinja2


build:
  skip: True  # [win or osx or py<35]

about:
  home: https://github.com/acs14007/easy_wrf
  summary: 'Easy WRF Installation on Linux'
  description: |
    The Weather Research and Forecasting (WRF) Model has many dependencies
    and is often challenging to install and set up. This package
    installs all WRF dependencies and generates install scripts and
    configuration files for WRF.

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - acs14007