# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "easy_wrf" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/acs14007/easy_wrf/releases/{{ version }}/simplejson-{{ version }}
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  # url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz
  # and otherwise fall back to archive:
  # url: https://github.com/simplejson/simplejson/archive/v{{ version }}.tar.gz

  sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge``

requirements:
  run:
    - python>=3.9
    - gfortran
    - gcc
    - cxx-compiler
    - boost-cpp
    - mpich
    - netcdf-cxx4
    - netcdf-fortran
    - netcdf4
    - jasper
    - libpng
    - zlib
    - hdf5
    - ncl
    - libssh
    - netcdf4
    - libnetcdf
    - netcdf-fortran
    - netcdf-cxx4

about:
  home: https://github.com/acs14007/easy_wrf
  summary: 'Easy WRF Installation on Linux'
  description: |
    The Weather Research and Forecasting (WRF) Model has many dependencies
    and is often challenging to install and set up. This package
    installs all WRF dependencies and generates install scripts and
    configuration files for WRF.

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - acs14007